const Allmember = [
    {
        id: 1,
        title: "Amritnendu",
        email:  'amritnendu@amritnendu.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      
      },
      {
        id: 2,
        title: "Saswati",
        email:  'saswati@writerzcenter.com',
        phone: '',
        designation:'',
        role:"Administrator",
        created: "March 24, 2024",
      },
      {
        id: 3,
        title: "Shreyasee",
        email:  'shreyasee@writerzcenter.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
      {
        id: 4,
        title: "Amritnendu",
        email:  'sneha@writerzcenter.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
      {
        id: 5,
        title: "Amritnendu",
        email:  'amritnendu@amritnendu.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
      {
        id: 6,
        title: "Amritnendu",
        email:  'amritnendu@amritnendu.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
      {
        id: 7,
        title: "Amritnendu",
        email:  'amritnendu@amritnendu.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
      {
        id: 8,
        title: "Amritnendu",
        email:  'amritnendu@amritnendu.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
      {
        id: 9,
        title: "Amritnendu",
        email:  'amritnendu@amritnendu.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
      {
        id: 10,
        title: "Amritnendu",
        email:  'amritnendu@amritnendu.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
      {
        id: 11,
        title: "Amritnendu",
        email:  'amritnendu@amritnendu.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
      {
        id: 12,
        title: "Amritnendu",
        email:  'amritnendu@amritnendu.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
      {
        id: 13,
        title: "Amritnendu",
        email:  'amritnendu@amritnendu.com',
        phone: '',
        designation:'',
        role:"Writer",
        created: "March 22, 2024",
      },
];
 
export default Allmember;
